[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "idioms"
version = "0.0.1"

[tool.setuptools]
package-dir = {"idioms" = "."}
packages = ["idioms", "idioms.idioms", "idioms.idioms.data", "idioms.idioms.data.idastubs"]
